"""
Scraper for parliamentary deputies.

Default output path generated by the scraper:
data/bronze/deputies/legislature=<n>/deputies.parquet
"""

import datetime
import hashlib
import logging
import os
import pathlib
import re
from typing import Any, Dict, List, Optional

import duckdb
import pandas as pd
from congreso_analisis.utils.selenium_utils import (
    accept_cookies,
    click_next_page,
    click_with_wait,
    init_driver,
    is_last_page,
    select_option_by_value,
    wait_for_spinner,
    wait_for_table_load,
)
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

# Enrichment is now handled via SubstitutionsEnricher in the Silver layer.

logger = logging.getLogger(__name__)


class DeputiesScraper:
    """
    Scraper to obtain the list of deputies and their basic data from the Congress website.
    """

    def __init__(
        self,
        driver_path: Optional[str] = None,
        term: str = "15",
        state_path: str = "state/bronze.duckdb",
        dataset: str = "deputies",
        headless: bool = True,
    ) -> None:
        """
        Initializes the DeputiesScraper.

        :param driver_path: Path to the ChromeDriver executable.
        :param term: Legislative term number (default: "15").
        :param state_path: Path to the DuckDB state file.
        :param dataset: Dataset identifier.
        """
        self.base_url = "https://www.congreso.es/busqueda-de-diputados"
        self.driver_path = driver_path
        self.term = term
        self.state_path = state_path
        self.dataset = dataset
        self.headless = headless
        self.driver: Any = None
        self.wait: Any = None
        self.db_conn: Any = None

    def _init_db(self) -> None:
        """Initializes DuckDB connection and ensures the state table exists."""
        db_path = os.path.abspath(self.state_path)
        os.makedirs(os.path.dirname(db_path) or ".", exist_ok=True)

        try:
            self.db_conn = duckdb.connect(db_path)
        except (UnicodeDecodeError, Exception) as e:
            logger.warning(f"Failed to connect to DuckDB using absolute path: {e}. Trying relative path...")
            try:
                # Try relative path as fallback
                self.db_conn = duckdb.connect(self.state_path)
            except Exception as e2:
                logger.error(f"Failed to connect to DuckDB using relative path: {e2}. State tracking will be disabled.")
                raise e2

        self.db_conn.execute(
            """
            CREATE TABLE IF NOT EXISTS bronze_documents (
                dataset VARCHAR,
                legislature VARCHAR,
                document_id VARCHAR,
                document_url VARCHAR,
                checksum VARCHAR,
                raw_path VARCHAR,
                last_extracted_at_utc VARCHAR,
                status VARCHAR,
                error_message VARCHAR,
                PRIMARY KEY (dataset, legislature, document_id)
            )
            """
        )

    def _get_document_state(self, document_id: str) -> Optional[Dict[str, Any]]:
        """Retrieves current document state from DuckDB."""
        if not self.db_conn:
            return None

        result = self.db_conn.execute(
            """
            SELECT checksum, status
            FROM bronze_documents
            WHERE dataset = ? AND legislature = ? AND document_id = ?
            """,
            [self.dataset, self.term, document_id],
        ).fetchone()

        if result:
            return {"checksum": result[0], "status": result[1]}
        return None

    def _update_document_state(
        self,
        document_id: str,
        document_url: str,
        checksum: str,
        raw_path: str,
        status: str,
        error_message: str = "",
    ) -> None:
        """Upserts a record into the DuckDB state store."""
        if not self.db_conn:
            return

        now_utc = datetime.datetime.now(datetime.timezone.utc).isoformat()

        self.db_conn.execute(
            """
            INSERT INTO bronze_documents (
                dataset, legislature, document_id, document_url,
                checksum, raw_path, last_extracted_at_utc, status, error_message
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (dataset, legislature, document_id) DO UPDATE SET
                document_url = excluded.document_url,
                checksum = excluded.checksum,
                raw_path = excluded.raw_path,
                last_extracted_at_utc = excluded.last_extracted_at_utc,
                status = excluded.status,
                error_message = excluded.error_message
            """,
            [self.dataset, self.term, document_id, document_url, checksum, raw_path, now_utc, status, error_message],
        )

    def _init_driver(self) -> None:
        """Initializes the Chrome driver."""
        self.driver, self.wait = init_driver(self.driver_path, headless=self.headless)

    def _search_deputies(self) -> None:
        """Applies filters on the website to start the search for deputies."""
        if not self.driver or not self.wait:
            return

        logger.info("Opening deputies search page...")
        self.driver.get(self.base_url)
        accept_cookies(self.driver, self.wait)

        logger.info("Waiting for the legislative term selector to load...")
        self.wait.until(EC.presence_of_element_located((By.ID, "_diputadomodule_legislatura")))

        logger.info(f"Selecting legislative term {self.term} if necessary...")
        term_select = self.driver.find_element(By.ID, "_diputadomodule_legislatura")
        if term_select.get_attribute("value") != self.term:
            select_option_by_value(term_select, self.term)
            logger.info(f"Legislative term {self.term} selected")

        logger.info("Selecting 'Todos' (All) in the type filter...")
        type_filter = self.driver.find_element(By.ID, "_diputadomodule_tipo")
        select_option_by_value(type_filter, "2")
        logger.info("'Todos' filter selected in type")

        logger.info("Clicking the search button...")
        click_with_wait(self.driver, self.wait, By.ID, "_diputadomodule_searchButtonDiputadosForm")

        logger.info("Waiting for the loading spinner to disappear...")
        wait_for_spinner(self.wait)

        logger.info("Waiting for the table results to be displayed...")
        wait_for_table_load(self.wait, "#_diputadomodule_contentPaginationDiputados table tbody tr")
        logger.info("Results loaded")

    def _extract_deputy_info(self, row: Any) -> Dict[str, str]:
        """
        Extracts the data of a deputy from a table row.

        :param row: Selenium WebElement representing a row in the table.
        :return: Dictionary with the extracted deputy information.
        """
        cells = row.find_elements(By.TAG_NAME, "td")
        link_element = row.find_element(By.TAG_NAME, "a")
        name = link_element.text.strip()
        url_ficha = link_element.get_attribute("href") or ""
        group = cells[0].text.strip() if len(cells) > 0 else ""
        constituency = cells[1].text.strip() if len(cells) > 1 else ""

        # Extract deputy_id from profile_url (codParlamentario parameter)
        deputy_id = ""
        match = re.search(r"codParlamentario=(\d+)", url_ficha)
        if match:
            deputy_id = match.group(1)

        return {
            "deputy_id": deputy_id,
            "name": name,
            "parliamentary_group": group,
            "constituency": constituency,
            "url_ficha": url_ficha,
            "term": self.term,
        }

    def _process_page(self) -> List[Dict[str, str]]:
        """
        Processes the results table of the current page and returns a list of deputies.

        :return: List of dictionaries with information for each deputy on the page.
        """
        if not self.driver or not self.wait:
            return []

        logger.info("Processing results page...")
        wait_for_table_load(self.wait, "#_diputadomodule_contentPaginationDiputados table tbody tr")
        rows = self.driver.find_elements(
            By.CSS_SELECTOR,
            "#_diputadomodule_contentPaginationDiputados table tbody tr",
        )
        logger.info(f"Number of deputies on this page: {len(rows)}")
        results = []
        for row in rows:
            try:
                data = self._extract_deputy_info(row)
                logger.info(
                    f"Deputy: {data['name']} - Group: {data['parliamentary_group']} "
                    f"- Constituency: {data['constituency']}"
                )
                results.append(data)
            except Exception as e:
                logger.error(f"Error extracting deputy info row: {e}")

        return results

    def _scrape_substitutions(self) -> pd.DataFrame:
        """
        Scrapes substitution events (Altas y Bajas) from the dedicated Congress page.

        :return: DataFrame with columns [name, substitutes, substituted_by, start_date, end_date]
        """
        url = "https://www.congreso.es/es/diputados-sustituidos-y-sustitutos"
        if not self.driver or not self.wait:
            return pd.DataFrame()

        logger.info(f"Opening substitutions page: {url}")
        self.driver.get(url)
        accept_cookies(self.driver, self.wait)

        logger.info(f"Selecting legislative term {self.term} for substitutions...")
        try:
            term_select = self.wait.until(EC.presence_of_element_located((By.ID, "_diputadomodule_legislatura")))
            if term_select.get_attribute("value") != self.term:
                select_option_by_value(term_select, self.term)

            # Click search button with JS to avoid being blocked by overlays/popovers
            try:
                # Use a very specific XPath and scroll into view
                search_btn = self.driver.find_element(By.XPATH, "//button[contains(text(), 'Buscar')]")
                self.driver.execute_script("arguments[0].scrollIntoView(true);", search_btn)
                self.driver.execute_script("arguments[0].click();", search_btn)
                logger.debug("Clicked search button via JS.")
            except Exception:
                # Fallback to any button that looks like a search button in the content
                self.driver.execute_script(
                    "document.querySelectorAll('button.btn').forEach(b => { "
                    "if(b.innerText.includes('Buscar')) b.click(); });"
                )

            # Wait for results to load (increased time and explicit spinner wait)
            import time

            from congreso_analisis.utils.selenium_utils import paginate_table

            time.sleep(8)
            wait_for_spinner(self.wait)

            substitutions = []

            paginator_id = "_diputadomodule_resultsShowedFooterSustituciones"
            next_btn_xpath = "//a[contains(@class, 'btn_pag') and text()='>']"

            try:
                for current_page_rows in paginate_table(
                    driver=self.driver,
                    wait=self.wait,
                    row_selector="table tr",
                    paginator_id=paginator_id,
                    next_btn_xpath=next_btn_xpath,
                    max_pages=500,
                ):
                    for row in current_page_rows:
                        try:
                            cells = row.find_elements(By.TAG_NAME, "td")
                            if not cells:
                                continue
                            main_cell = cells[0]
                            links = main_cell.find_elements(By.TAG_NAME, "a")
                            if not links:
                                continue

                            name = links[0].text.strip()
                            rel_text = main_cell.text.lower()
                            substitutes = ""
                            substituted_by = ""

                            # Robust parsing of relationship text
                            # Variations in Spanish: Sustituye a, Sustituyó a, Sustituida por, Sustituido por
                            if "sustituy" in rel_text:
                                # If it's incoming: "Sustituye a:" or "Sustituyó a:"
                                if "sustituy" in rel_text and " por" not in rel_text:
                                    if len(links) > 1:
                                        substitutes = links[1].text.strip()
                                    else:
                                        # Fallback parsing
                                        parts = re.split(r"sustituy\w* a[: ]*", rel_text, flags=re.IGNORECASE)
                                        if len(parts) > 1:
                                            substitutes = parts[1].split("\n")[0].strip()

                            if "sustituid" in rel_text or " por" in rel_text:
                                # If it's outgoing: "Sustituido por:" or "Sustituida por:"
                                if len(links) > 1:
                                    substituted_by = links[1].text.strip()
                                else:
                                    parts = re.split(r"sustituid\w* por[: ]*", rel_text, flags=re.IGNORECASE)
                                    if len(parts) > 1:
                                        substituted_by = parts[1].split("\n")[0].strip()

                            start_date = cells[1].text.strip() if len(cells) > 1 else ""
                            end_date = cells[2].text.strip() if len(cells) > 2 else ""

                            substitutions.append(
                                {
                                    "name": name,
                                    "substitutes": substitutes,
                                    "substituted_by": substituted_by,
                                    "start_date": start_date,
                                    "end_date": end_date,
                                }
                            )
                        except Exception:
                            continue
            except Exception as e:
                logger.error(f"Error paginating substitutions: {e}")

            return pd.DataFrame(substitutions)

        except Exception as e:
            logger.error(f"Error scraping substitutions: {e}")
            return pd.DataFrame()

    def _calculate_checksum(self, df: pd.DataFrame) -> str:
        """
        Calculates a deterministic SHA256 checksum for the dataframe.

        :param df: Pandas DataFrame to hash.
        :return: SHA256 string representation of the dataframe contents.
        """
        if df.empty:
            return hashlib.sha256(b"").hexdigest()

        # Create a copy to not modify the original
        df_hash = df.copy()

        # Sort columns to ensure consistent order
        df_hash = df_hash.reindex(sorted(df_hash.columns), axis=1)

        # Sort rows by 'name' deterministically (or any stable key)
        df_hash = df_hash.sort_values(by="name").reset_index(drop=True)

        # Serialize to CSV string and encode to bytes
        csv_bytes = df_hash.to_csv(index=False).encode("utf-8")
        return hashlib.sha256(csv_bytes).hexdigest()

    def run(
        self,
        output_root: str = "data/bronze",
        output_filename: str = "deputies.parquet",
    ) -> pd.DataFrame:
        """
        Executes the full scraping process, including deputies and substitutions,
        adds metadata, and saves results to Parquet files in the Bronze data lake.

        :param output_root: Root directory for the Bronze layer (default: "data/bronze").
        :param output_filename: Output Parquet filename for deputies (default: "deputies.parquet").
        :return: Pandas DataFrame with the extracted deputies results.
        """
        self._init_db()

        # 1. Scrape Deputies
        self._init_driver()
        document_id = f"deputies_snapshot_term_{self.term}"
        all_results: List[Dict[str, str]] = []

        try:
            self._search_deputies()
            while True:
                all_results.extend(self._process_page())
                possible_ids = [
                    "_diputadomodule_resultsShowedDiputados",
                    "_diputadomodule_resultsShowedFooterDiputados",
                ]
                if any(is_last_page(self.driver, id_) for id_ in possible_ids):
                    logger.info("Last page detected.")
                    break

                if not click_next_page(
                    driver=self.driver,
                    wait=self.wait,
                    next_xpath="//ul[@id='_diputadomodule_paginationLinksDiputados']//a[text()='>']",
                    table_by=By.CSS_SELECTOR,
                    table_selector="#_diputadomodule_contentPaginationDiputados table tbody tr",
                    paginator_id="_diputadomodule_resultsShowedFooterDiputados",
                ):
                    break
        except Exception as e:
            self._update_document_state(document_id, self.base_url, "", "", "ERROR", str(e))
            logger.error(f"An error occurred during deputies scraping: {e}")
        finally:
            if self.driver:
                self.driver.quit()

        df_deputies = pd.DataFrame(all_results)

        # 2. Scrape Substitutions
        self._init_driver()  # Re-init driver for the new page
        df_substitutions = pd.DataFrame()
        sub_document_id = f"substitutions_snapshot_term_{self.term}"
        url = "https://www.congreso.es/es/diputados-sustituidos-y-sustitutos"
        try:
            df_substitutions = self._scrape_substitutions()
        except Exception as e:
            logger.error(f"Failed to scrape substitutions: {e}")
        finally:
            if self.driver:
                self.driver.quit()

        # 3. Process and Save Deputies
        if not df_deputies.empty:
            df_deputies["dataset"] = self.dataset
            df_deputies["source_url"] = self.base_url
            df_deputies["extracted_at_utc"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
            df_deputies["legislature"] = self.term

            checksum = self._calculate_checksum(df_deputies)
            df_deputies["checksum"] = checksum
            state = self._get_document_state(document_id)

            output_dir = pathlib.Path(output_root) / self.dataset / f"legislature={self.term}"
            output_dir.mkdir(parents=True, exist_ok=True)
            output_path = output_dir / output_filename

            if state and state["status"] == "SUCCESS" and state["checksum"] == checksum and output_path.exists():
                logger.info(f"Skipping identical cached document for deputies: {document_id}")
            else:
                try:
                    df_deputies.to_parquet(str(output_path), index=False)
                    self._update_document_state(document_id, self.base_url, checksum, str(output_path), "SUCCESS")
                    logger.info(f"Saved Parquet with {len(df_deputies)} rows to {output_path}")
                except Exception as e:
                    logger.error(f"Failed to save deputies parquet: {e}")

        # 4. Process and Save Substitutions
        if not df_substitutions.empty:
            df_substitutions["dataset"] = "substitutions"
            df_substitutions["legislature"] = self.term
            df_substitutions["extracted_at_utc"] = datetime.datetime.now(datetime.timezone.utc).isoformat()

            sub_checksum = self._calculate_checksum(df_substitutions)
            sub_state = self._get_document_state(sub_document_id)

            sub_output_dir = pathlib.Path(output_root) / "substitutions" / f"legislature={self.term}"
            sub_output_dir.mkdir(parents=True, exist_ok=True)
            sub_output_path = sub_output_dir / "substitutions.parquet"

            if (
                sub_state
                and sub_state["status"] == "SUCCESS"
                and sub_state["checksum"] == sub_checksum
                and sub_output_path.exists()
            ):
                logger.info(f"Skipping identical cached document for substitutions: {sub_document_id}")
            else:
                df_substitutions.to_parquet(str(sub_output_path), index=False)
                self.db_conn.execute(
                    """
                    INSERT INTO bronze_documents (
                        dataset, legislature, document_id, document_url,
                        checksum, raw_path, last_extracted_at_utc, status
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT (dataset, legislature, document_id) DO UPDATE SET
                        checksum = excluded.checksum,
                        raw_path = excluded.raw_path,
                        last_extracted_at_utc = excluded.last_extracted_at_utc,
                        status = excluded.status
                    """,
                    [
                        "substitutions",
                        self.term,
                        sub_document_id,
                        url,
                        sub_checksum,
                        str(sub_output_path),
                        datetime.datetime.now(datetime.timezone.utc).isoformat(),
                        "SUCCESS",
                    ],
                )
                logger.info(f"Saved Substitutions Parquet with {len(df_substitutions)} rows to {sub_output_path}")

        if self.db_conn:
            self.db_conn.close()

        return df_deputies
