"""
Scraper for parliamentary groups.

Default output path generated by the scraper:
data/bronze/groups/legislature=15/groups.parquet
"""

import datetime
import hashlib
import logging
import os
import pathlib
from typing import Any, Dict, List, Optional, Tuple

import duckdb
import pandas as pd
from congreso_analisis.utils.selenium_utils import (
    accept_cookies,
    click_siguiente_pagina,
    click_with_wait,
    init_driver,
    is_last_page,
    select_option_by_value,
    wait_for_spinner,
    wait_for_table_load,
)
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

logger = logging.getLogger(__name__)


class GroupsScraper:
    """
    Scraper for parliamentary groups from the Congress website.
    """

    def __init__(
        self,
        driver_path: Optional[str] = None,
        term: str = "15",
        state_path: str = "state/bronze.duckdb",
        dataset: str = "groups",
        headless: bool = True,
    ) -> None:
        """
        Initializes the GroupsScraper.

        :param driver_path: Path to the ChromeDriver executable, optional.
        :param term: Legislative term number (default: "15").
        :param state_path: Path to the DuckDB state file.
        :param dataset: Dataset identifier.
        """
        self.base_url = "https://www.congreso.es/es/grupos/composicion-en-la-legislatura"
        self.driver_path = driver_path
        self.term = term
        self.state_path = state_path
        self.dataset = dataset
        self.headless = headless
        self.driver: Any = None
        self.wait: Any = None
        self.db_conn: Any = None

    def _init_db(self) -> None:
        """Initializes DuckDB connection and ensures the state table exists."""
        db_path = os.path.abspath(self.state_path)
        os.makedirs(os.path.dirname(db_path) or ".", exist_ok=True)

        try:
            self.db_conn = duckdb.connect(db_path)
        except (UnicodeDecodeError, Exception) as e:
            logger.warning(f"Failed to connect to DuckDB using absolute path: {e}. Trying relative path...")
            try:
                # Try relative path as fallback
                self.db_conn = duckdb.connect(self.state_path)
            except Exception as e2:
                logger.error(f"Failed to connect to DuckDB using relative path: {e2}. State tracking will be disabled.")
                raise e2

        self.db_conn.execute(
            """
            CREATE TABLE IF NOT EXISTS bronze_documents (
                dataset VARCHAR,
                legislature VARCHAR,
                document_id VARCHAR,
                document_url VARCHAR,
                checksum VARCHAR,
                raw_path VARCHAR,
                last_extracted_at_utc VARCHAR,
                status VARCHAR,
                error_message VARCHAR,
                PRIMARY KEY (dataset, legislature, document_id)
            )
            """
        )

    def _get_document_state(self, document_id: str) -> Optional[Dict[str, Any]]:
        """Retrieves current document state from DuckDB."""
        if not self.db_conn:
            return None

        result = self.db_conn.execute(
            """
            SELECT checksum, status
            FROM bronze_documents
            WHERE dataset = ? AND legislature = ? AND document_id = ?
            """,
            [self.dataset, self.term, document_id],
        ).fetchone()

        if result:
            return {"checksum": result[0], "status": result[1]}
        return None

    def _update_document_state(
        self,
        document_id: str,
        document_url: str,
        checksum: str,
        raw_path: str,
        status: str,
        error_message: str = "",
    ) -> None:
        """Upserts a record into the DuckDB state store."""
        if not self.db_conn:
            return

        now_utc = datetime.datetime.now(datetime.timezone.utc).isoformat()

        self.db_conn.execute(
            """
            INSERT INTO bronze_documents (
                dataset, legislature, document_id, document_url,
                checksum, raw_path, last_extracted_at_utc, status, error_message
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (dataset, legislature, document_id) DO UPDATE SET
                document_url = excluded.document_url,
                checksum = excluded.checksum,
                raw_path = excluded.raw_path,
                last_extracted_at_utc = excluded.last_extracted_at_utc,
                status = excluded.status,
                error_message = excluded.error_message
            """,
            [self.dataset, self.term, document_id, document_url, checksum, raw_path, now_utc, status, error_message],
        )

    def _calculate_checksum(self, df: pd.DataFrame) -> str:
        """Calculates a deterministic SHA256 checksum for the dataframe."""
        if df.empty:
            return hashlib.sha256(b"").hexdigest()

        df_hash = df.copy()
        df_hash = df_hash.reindex(sorted(df_hash.columns), axis=1)
        # Groups don't always have names, sort by whichever key makes sense or combination
        sort_cols = [c for c in ["parliamentary_group", "name", "addition_date"] if c in df_hash.columns]
        if sort_cols:
            df_hash = df_hash.sort_values(by=sort_cols).reset_index(drop=True)

        csv_bytes = df_hash.to_csv(index=False).encode("utf-8")
        return hashlib.sha256(csv_bytes).hexdigest()

    def _init_driver(self) -> None:
        """
        Initializes the Chrome driver.
        """
        self.driver, self.wait = init_driver(self.driver_path, headless=self.headless)

    def _extract_term_info(self) -> List[Tuple[str, str]]:
        """
        Extracts information about the parliamentary groups for the current term.

        :return: A list of tuples containing (group_name, group_url).
        """
        if not self.driver or not self.wait:
            return []

        self.driver.get(self.base_url)
        accept_cookies(self.driver, self.wait)
        wait_for_spinner(self.wait)

        logger.info("Selecting legislative term...")
        term_select = self.driver.find_element(By.ID, "_grupos_legislatura")
        select_option_by_value(term_select, self.term)

        wait_for_spinner(self.wait)
        self.wait.until(EC.presence_of_element_located((By.ID, "_grupos_ajaxContentGrupo")))

        links = self.driver.find_elements(By.CSS_SELECTOR, "#_grupos_ajaxContentGrupo a")
        result = [(link.text.strip().split(":")[0], link.get_attribute("href") or "") for link in links]
        return result

    def _extract_additions_and_removals(self, group_name: str, url: str) -> List[Dict[str, str]]:
        """
        Accesses the parliamentary group page and extracts additions
        and removals of its deputies.

        :param group_name: Name of the parliamentary group (e.g., 'PSOE').
        :param url: Specific URL for the parliamentary group.
        :return: List of dictionaries with name, addition_date, and removal_date.
        """
        if not self.driver or not self.wait:
            return []

        self.driver.get(url)
        wait_for_spinner(self.wait)

        try:
            # Click on the "Altas y bajas" radio button
            click_with_wait(self.driver, self.wait, By.ID, "_grupos_altaBajaA")
            wait_for_spinner(self.wait)
            self.wait.until(EC.presence_of_element_located((By.ID, "_grupos_ajaxContentDiputados")))
            wait_for_table_load(self.wait, "#_grupos_contentPaginationDiputados table tbody tr")
        except Exception as e:
            logger.error(f"Could not select 'Altas y bajas' for {group_name}: {e}")
            return []

        data: List[Dict[str, str]] = []
        while True:
            rows = self.driver.find_elements(By.CSS_SELECTOR, "#_grupos_contentPaginationDiputados table tbody tr")
            for row in rows:
                try:
                    # Name in <th>
                    name = row.find_element(By.TAG_NAME, "th").text.strip()

                    # Dates in <td>
                    columns = row.find_elements(By.TAG_NAME, "td")
                    addition_date = columns[0].text.strip() if len(columns) > 0 else ""
                    removal_date = columns[1].text.strip() if len(columns) > 1 else ""

                    if name:
                        data.append(
                            {
                                "name": name,
                                "parliamentary_group": group_name,
                                "addition_date": addition_date,
                                "removal_date": removal_date,
                                "term": self.term,
                            }
                        )
                except Exception as e:
                    logger.error(f"Error processing row in {group_name}: {e}")
                    continue

            if is_last_page(self.driver, "_grupos_resultsShowedFooterDiputados"):
                break

            if not click_siguiente_pagina(
                driver=self.driver,
                wait=self.wait,
                next_xpath="//ul[@id='_grupos_paginationLinksDiputados']//a[text()='>']",
                table_by=By.CSS_SELECTOR,
                table_selector="#_grupos_contentPaginationDiputados table tbody tr",
                paginator_id="_grupos_resultsShowedFooterDiputados",
            ):
                break

        return data

    def run(self, output_root: str = "data/bronze", output_filename: str = "groups.parquet") -> None:
        """
        Executes the scraping process and saves the data to a Parquet file
        in a Bronze data lake structure, tracking idempotency state.

        :param output_root: Root directory for the Bronze layer (default: "data/bronze").
        :param output_filename: Output Parquet filename (default: "groups.parquet").
        """
        self._init_db()
        self._init_driver()

        # We classify groups dataset as a whole snapshot (1 document logically per term)
        document_id = f"groups_snapshot_term_{self.term}"

        try:
            logger.info("Accessing parliamentary groups...")
            group_links = self._extract_term_info()

            all_data: List[Dict[str, str]] = []
            for group_name, url in group_links:
                logger.info(f"Processing group: {group_name}")
                data = self._extract_additions_and_removals(group_name, url)
                logger.info(f"  -> Extracted {len(data)} deputies")
                all_data.extend(data)

            df = pd.DataFrame(all_data)

            # Add technical metadata
            df["dataset"] = self.dataset
            df["source_url"] = self.base_url
            df["extracted_at_utc"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
            df["legislature"] = self.term

            checksum = self._calculate_checksum(df)
            df["checksum"] = checksum

            state = self._get_document_state(document_id)

            # Bronze data lake path construction
            output_dir = pathlib.Path(output_root) / self.dataset / f"legislature={self.term}"
            output_dir.mkdir(parents=True, exist_ok=True)
            output_path = output_dir / output_filename

            # If the checksum is exactly the same, we do not write a new parquet file
            if state and state["status"] == "SUCCESS" and state["checksum"] == checksum and output_path.exists():
                logger.info(f"Skipping identical cached document for group deputies: {document_id}")
            else:
                try:
                    df.to_parquet(str(output_path), index=False)
                    self._update_document_state(document_id, self.base_url, checksum, str(output_path), "SUCCESS")
                    logger.info(f"Saved Parquet with {len(df)} rows to {output_path}")
                except Exception as e:
                    self._update_document_state(document_id, self.base_url, checksum, "", "ERROR", str(e))
                    logger.error(f"Error saving {document_id}: {e}")

        except Exception as e:
            self._update_document_state(document_id, self.base_url, "", "", "ERROR", str(e))
        finally:
            if self.driver:
                self.driver.quit()
            if self.db_conn:
                self.db_conn.close()
