"""
Scraper for parliamentary sessions (Diarios de Sesiones).

Default output paths generated by the scraper:
Raw HTML: data/raw/sessions/legislature=<n>/<document_id>.html
Bronze Metadata: data/bronze/sessions/legislature=<n>/sessions.parquet
State DB: state/bronze.duckdb
"""

import datetime
import hashlib
import logging
import os
import pathlib
import re
import time
from typing import Any, Dict, List, Optional

import duckdb
import pandas as pd
from congreso_analisis.utils.selenium_utils import (
    accept_cookies,
    click_next_page,
    click_with_wait,
    init_driver,
    select_option_by_value,
)
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select

logger = logging.getLogger(__name__)


class SessionsScraper:
    """
    Scraper to obtain the list of parliamentary sessions (Diarios de Sesiones) and download their raw HTML content.
    """

    def __init__(
        self,
        driver_path: Optional[str] = None,
        term: str = "15",
        raw_root: str = "data/raw",
        bronze_root: str = "data/bronze",
        state_path: str = "state/bronze.duckdb",
        dataset: str = "sessions",
        headless: bool = True,
    ) -> None:
        """
        Initializes the SessionsScraper.

        :param driver_path: Path to the ChromeDriver executable.
        :param term: Legislative term number (default: "15").
        :param raw_root: Directory for raw HTML outputs.
        :param bronze_root: Directory for parquet metadata.
        :param state_path: Path to the DuckDB state file.
        :param dataset: Dataset identifier.
        :param headless: Whether to run Chrome in headless mode.
        """
        self.base_url = "https://www.congreso.es/busqueda-de-publicaciones"
        self.driver_path = driver_path
        self.term = term
        self.raw_root = raw_root
        self.bronze_root = bronze_root
        self.state_path = state_path
        self.dataset = dataset
        self.headless = headless

        self.driver: Any = None
        self.wait: Any = None
        self.db_conn: Any = None

    def _init_db(self) -> None:
        """Initializes DuckDB connection and ensures the state table exists."""
        db_path = os.path.abspath(self.state_path)
        os.makedirs(os.path.dirname(db_path) or ".", exist_ok=True)

        try:
            self.db_conn = duckdb.connect(db_path)
        except (UnicodeDecodeError, Exception) as e:
            logger.warning(f"Failed to connect to DuckDB using absolute path: {e}. Trying relative path...")
            try:
                # Try relative path as fallback
                self.db_conn = duckdb.connect(self.state_path)
            except Exception as e2:
                logger.error(f"Failed to connect to DuckDB using relative path: {e2}. State tracking will be disabled.")
                raise e2

        self.db_conn.execute(
            """
            CREATE TABLE IF NOT EXISTS bronze_documents (
                dataset VARCHAR,
                legislature VARCHAR,
                document_id VARCHAR,
                document_url VARCHAR,
                checksum VARCHAR,
                raw_path VARCHAR,
                last_extracted_at_utc VARCHAR,
                status VARCHAR,
                error_message VARCHAR,
                PRIMARY KEY (dataset, legislature, document_id)
            )
            """
        )

    def _init_driver(self) -> None:
        """Initializes the Chrome driver."""
        self.driver, self.wait = init_driver(self.driver_path, headless=self.headless)

    def _apply_filters(self) -> None:
        """Applies filters on the website to start the search for sessions."""
        if not self.driver or not self.wait:
            return

        logger.info("Opening publications search page...")
        self.driver.get(self.base_url)
        accept_cookies(self.driver, self.wait)

        logger.info("Waiting for the legislative term selector to load...")
        self.wait.until(EC.presence_of_element_located((By.ID, "_publicaciones_legislatura")))

        logger.info(f"Applying filters for legislature {self.term}...")

        # Select the legislature
        select_element = Select(self.driver.find_element(By.ID, "_publicaciones_legislatura"))
        for option in select_element.options:
            value = option.get_attribute("value")
            if value.startswith(self.term):
                option.click()
                break
        else:
            # Fallback to direct select if startswith logic fails
            Select(self.driver.find_element(By.ID, "_publicaciones_legislatura")).select_by_value(self.term)

        # 'D' value corresponds to 'Diarios de Sesiones'. If the user wants to ensure exact text, we can use it.
        try:
            select_pub = Select(self.driver.find_element(By.ID, "publicacion"))
            select_pub.select_by_visible_text("Diarios de Sesiones")
        except Exception:
            select_option_by_value(self.driver.find_element(By.ID, "publicacion"), "D")

        # 'CONGRESO' for Sección. Visibility check for "Congreso de los Diputados".
        try:
            select_sec = Select(self.driver.find_element(By.ID, "seccion"))
            select_sec.select_by_visible_text("Congreso de los Diputados")
        except Exception:
            select_option_by_value(self.driver.find_element(By.ID, "seccion"), "CONGRESO")

        # Set Organo to 'Pleno-y-Diputación-Permanente'
        try:
            # It can be 'serieOrgano' or 'organo' depending on the version of the page
            organo_elem = None
            for eid in ["serieOrgano", "organo"]:
                try:
                    organo_elem = self.driver.find_element(By.ID, eid)
                    break
                except Exception:
                    continue

            if organo_elem:
                target_value = "Pleno-y-Diputación-Permanente"
                logger.info(f"Setting Organo filter to '{target_value}'...")

                # Clear and type since it's an auto-complete
                organo_elem.clear()
                organo_elem.send_keys(target_value)
                time.sleep(1)
                organo_elem.send_keys(Keys.ENTER)
        except Exception as e:
            logger.warning(f"Could not set 'Pleno-y-Diputación-Permanente' filter: {e}")

        logger.info("Clicking the search button...")
        click_with_wait(
            self.driver,
            self.wait,
            By.XPATH,
            "//button[.//span[normalize-space(text())='Buscar']]",
        )

        logger.info("Waiting for the results to load...")
        # Broaden the selector to be more robust
        table_selector = (
            "//tr[td//a[contains(@href, '/public_oficiales/') or "
            "contains(@href, 'TextoIntegro') or contains(@href, 'id_texto=')]]"
        )
        self.wait.until(EC.presence_of_element_located((By.XPATH, table_selector)))
        logger.info("Results loaded")

    def _calculate_checksum(self, html_content: str) -> str:
        """Calculates a deterministic SHA256 checksum for the HTML content."""
        return hashlib.sha256(html_content.encode("utf-8")).hexdigest()

    def _get_document_state(self, document_id: str) -> Optional[Dict[str, Any]]:
        """Retrieves current document state from DuckDB."""
        if not self.db_conn:
            return None

        result = self.db_conn.execute(
            """
            SELECT checksum, status
            FROM bronze_documents
            WHERE dataset = ? AND legislature = ? AND document_id = ?
            """,
            [self.dataset, self.term, document_id],
        ).fetchone()

        if result:
            return {"checksum": result[0], "status": result[1]}
        return None

    def _update_document_state(
        self,
        document_id: str,
        document_url: str,
        checksum: str,
        raw_path: str,
        status: str,
        error_message: str = "",
    ) -> None:
        """Upserts a record into the DuckDB state store."""
        if not self.db_conn:
            return

        now_utc = datetime.datetime.now(datetime.timezone.utc).isoformat()

        self.db_conn.execute(
            """
            INSERT INTO bronze_documents (
                dataset, legislature, document_id, document_url,
                checksum, raw_path, last_extracted_at_utc, status, error_message
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (dataset, legislature, document_id) DO UPDATE SET
                document_url = excluded.document_url,
                checksum = excluded.checksum,
                raw_path = excluded.raw_path,
                last_extracted_at_utc = excluded.last_extracted_at_utc,
                status = excluded.status,
                error_message = excluded.error_message
            """,
            [self.dataset, self.term, document_id, document_url, checksum, raw_path, now_utc, status, error_message],
        )

    def _save_raw_html(self, document_id: str, html_content: str) -> str:
        """Saves the raw HTML portlet to the filesystem and returns the path."""
        out_dir = pathlib.Path(self.raw_root) / self.dataset / f"legislature={self.term}"
        out_dir.mkdir(parents=True, exist_ok=True)

        file_path = out_dir / f"{document_id}.html"
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        return str(file_path)

    def _extract_portlet_html(self, document_url: str) -> Optional[str]:
        """Opens a new tab, navigates to the document URL, extracts portlet HTML, and closes the tab."""
        if not self.driver or not self.wait:
            return None

        # Process in new tab to preserve search results state
        self.driver.execute_script("window.open(arguments[0]);", document_url)
        self.driver.switch_to.window(self.driver.window_handles[-1])

        html_content = None
        try:
            # Added a slight delay for Akamai / anti-bot protection when opening new tabs directly
            import time

            time.sleep(3)
            self.wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
            # Find the portlet block
            portlet = self.driver.find_element(By.CSS_SELECTOR, "section#portlet_publicaciones")
            html_content = portlet.get_attribute("outerHTML")
        except Exception as e:
            logger.error(f"Error extracting HTML from {document_url}: {e}")
        finally:
            self.driver.close()
            # Restore main window focus
            self.driver.switch_to.window(self.driver.window_handles[0])

        return html_content

    def _process_row(self, row: Any) -> Optional[Dict[str, Any]]:
        """
        Processes a single row from the publications table.

        :param row: Selenium WebElement representing the table row.
        :return: A dictionary with metadata if successfully parsed, None otherwise.
        """
        # 1. Parse table info to generate ID
        cells = row.find_elements(By.TAG_NAME, "td")
        if not cells:
            return None

        row_text = row.text

        # Extract session date using regex search across all cells
        session_date = ""
        for cell in cells:
            date_match = re.search(r"(\d{2}/\d{2}/\d{4})", cell.text)
            if date_match:
                session_date = date_match.group(1)
                break

        # Only process Diarios de Sesiones Plenos if matching classic format
        is_plenary = "-PL-" in row_text or "Pleno" in row_text

        if not is_plenary:
            return None

        # Extract publication code like: DSCD-15-PL-12
        publication_code = ""
        cve = ""
        for td in cells:
            cell_text = td.text.strip()
            if "DSCD" in cell_text:
                publication_code = cell_text
            if "cve:" in cell_text or re.search(r"[A-Z]{2,4}-[A-Z0-9\-]+", cell_text):
                cve = cell_text.replace("cve:", "").strip()

        # Derive stable document_id
        document_id = ""
        if publication_code:
            match = re.search(r"(DSCD-\d+(?:-PL-\d+)?)", publication_code)
            if match:
                document_id = match.group(1)

        if not document_id and cve:
            document_id = cve

        # Fallback to URL parameter or hash
        if not document_id:
            try:
                # Try to find any link in the row
                link_elem = row.find_element(By.TAG_NAME, "a")
                href = link_elem.get_attribute("href") or ""
                match_id = re.search(r"id_texto=([^&]+)", href)
                if match_id:
                    document_id = match_id.group(1)
                else:
                    document_id = hashlib.sha1(href.encode("utf-8")).hexdigest()
            except Exception:
                return None

        try:
            # Try to find "Texto íntegro" or fallback to any link
            try:
                texto_link = row.find_element(By.XPATH, ".//a[contains(text(),'Texto íntegro')]")
            except Exception:
                texto_link = row.find_element(By.TAG_NAME, "a")
            document_url = texto_link.get_attribute("href") or ""
        except Exception:
            return None

        # 2. Check DuckDB state for idempotency
        state = self._get_document_state(document_id)
        expected_raw_path = (
            pathlib.Path(self.raw_root) / self.dataset / f"legislature={self.term}" / f"{document_id}.html"
        )

        if state and state["status"] == "SUCCESS" and expected_raw_path.exists():
            logger.info(f"Skipping already downloaded document: {document_id}")
            checksum = state["checksum"]
            raw_path = str(expected_raw_path)

            # Build Metadata Row
            return {
                "dataset": self.dataset,
                "source_url": self.base_url,
                "document_url": document_url,
                "document_id": document_id,
                "raw_path": raw_path,
                "extracted_at_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                "checksum": checksum,
                "legislature": self.term,
                "publication_code": publication_code or document_id,
                "is_plenary": is_plenary,
                "session_date": session_date,
            }

        logger.info(f"Processing document {document_id} from {document_url}")

        html_content = self._extract_portlet_html(document_url)
        if not html_content:
            self._update_document_state(document_id, document_url, "", "", "ERROR", "Failed to extract portlet HTML")
            return None

        checksum = self._calculate_checksum(html_content)

        try:
            raw_path = self._save_raw_html(document_id, html_content)
            self._update_document_state(document_id, document_url, checksum, raw_path, "SUCCESS")
            logger.info(f"Saved new or updated document: {document_id}")
        except Exception as e:
            self._update_document_state(document_id, document_url, checksum, "", "ERROR", str(e))
            logger.error(f"Error saving {document_id}: {e}")
            return None

        # Build Metadata Row
        return {
            "dataset": self.dataset,
            "source_url": self.base_url,
            "document_url": document_url,
            "document_id": document_id,
            "raw_path": raw_path,
            "extracted_at_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "checksum": checksum,
            "legislature": self.term,
            "publication_code": publication_code or document_id,
            "is_plenary": is_plenary,
            "session_date": session_date,
        }

    def run(self) -> pd.DataFrame:
        """
        Executes the scraping process for parliamentary sessions, maintaining idempotent state
        with DuckDB and persisting output to Raw HTML and Bronze Parquet structures.

        :return: Pandas DataFrame containing metadata of the processed documents.
        """
        self._init_db()
        self._init_driver()

        metadata_records: List[Dict[str, Any]] = []

        try:
            self._apply_filters()

            page = 1
            xpath_next = "//ul[@id='_publicaciones_paginationLinksPublicaciones']//a[text()='>']"
            table_selector = (
                "//tr[td//a[contains(@href, '/public_oficiales/') or "
                "contains(@href, 'TextoIntegro') or contains(@href, 'id_texto=')]]"
            )

            while True:
                logger.info(f"Processing Page {page}")

                # Using wait_for_table_load with xpath isn't directly supported by our generic util without tweaks
                # so we rely on explicit presence finds below
                self.wait.until(EC.presence_of_element_located((By.XPATH, table_selector)))
                rows = self.driver.find_elements(By.XPATH, table_selector)

                logger.info(f"Found {len(rows)} potential session documents.")

                for i in range(len(rows)):
                    for _ in range(3):  # Retry mechanism for stale elements
                        try:
                            # Refetch in case DOM changed
                            fresh_rows = self.driver.find_elements(By.XPATH, table_selector)
                            if i < len(fresh_rows):
                                record = self._process_row(fresh_rows[i])
                                if record:
                                    metadata_records.append(record)
                            break
                        except Exception as e:
                            logger.warning(f"Error processing row {i} on attempt, retrying... {e}")

                # Check if last page text indicator exists
                try:
                    paginator_text = self.driver.find_element(By.ID, "_publicaciones_resultsShowedPublicaciones").text

                    # Usually "Resultados X a Y de Z"
                    match = re.search(r"Resultados \d+ a (\d+) de (\d+)", paginator_text)
                    if match and match.group(1) == match.group(2):
                        logger.info("Last page detected via text limits.")
                        break
                except Exception:
                    pass

                # Try clicking next page using utility
                if not click_next_page(self.driver, self.wait, xpath_next, By.XPATH, table_selector):
                    logger.info("No next page link found.")
                    break

                page += 1

        except Exception as e:
            logger.error(f"Critical error during sessions scraping: {e}")
        finally:
            if self.driver:
                self.driver.quit()
            if self.db_conn:
                self.db_conn.close()

        # Generate Parquet Metadata
        df = pd.DataFrame(metadata_records)

        if not df.empty:
            out_dir = pathlib.Path(self.bronze_root) / self.dataset / f"legislature={self.term}"
            out_dir.mkdir(parents=True, exist_ok=True)
            parquet_path = out_dir / f"{self.dataset}.parquet"

            df.to_parquet(str(parquet_path), index=False)
            logger.info(f"Saved Metadata Parquet with {len(df)} rows to {parquet_path}")
        else:
            logger.warning("No records were successfully scraped to create the Parquet metadata.")

        return df
